SOURCES = Camera.cpp Encoder.cpp Network.cpp RtpPacketizer.cpp TextMessageServer.cpp TextMessageClient.cpp TextMessageTransport.cpp Thread.cpp
PRODUCT := infra
LIBS := cube

-include ../makelib.mk
